name: Build and Publish Docker Image

on:
  push:
    branches: ["main"] # Otomatis berjalan setiap ada push ke branch main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Otomatis mengambil format: username-anda/nama-repo-anda

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Izin penting agar GitHub Actions bisa menyimpan image ke GHCR Anda

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token rahasia yang otomatis disediakan GitHub

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
